server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal/loki/api/v1/push

scrape_configs:
  - job_name: log
    static_configs:
      - targets:
          - localhost
        labels:
          job: was_logs
          __path__: /logs
